### ISSUE TITLE
Skriptfehler bei nichtexistenter Waffe (?)

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_GameOfGuns.Altis#48]
```
21:54:42 Error in expression <pe == "NUMBER") exitWith {
if (isNumber _configEntry || {isText _configEntry}) t>
21:54:42   Error position: <_configEntry || {isText _configEntry}) t>
21:54:42   Error Undefined variable in expression: _configentry
21:54:42 File \x\cba\addons\common\fnc_getConfigEntry.sqf [CBA_fnc_getConfigEntry], line 1835
21:54:42 Error in expression <ank = ([configFile >> "CfgMagazines" >> _magazine >> "initSpeed", "number", 900]>
21:54:42   Error position: <_magazine >> "initSpeed", "number", 900]>
21:54:42   Error Undefined variable in expression: _magazine
21:54:42 File functions\missionSetup\fn_applyWeapon.sqf [gungame_missionSetup_fnc_applyWeapon], line 1848
```

**Comment by dedmen** [comment]
`functions\missionSetup\fn_applyWeapon.sqf [gungame_missionSetup_fnc_applyWeapon], line 1848`
wtf?
I found that line of code here:
https://github.com/gruppe-adler/TvT_GameOfGuns.Altis/blob/51b5edc1d351b52c147ae2c2c7411f13f7bedbeb/functions/fn_upgradeWeapon.sqf#L29
That's a different file and function name and line.


https://github.com/gruppe-adler/TvT_GameOfGuns.Altis/blob/51b5edc1d351b52c147ae2c2c7411f13f7bedbeb/functions/fn_upgradeWeapon.sqf#L25

Here's the error. magazines array might be empty since we got magazineWells.

Use this https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_compatibleMagazines.sqf

Also wtf is up with the mixing of / and >> and the private array?
